export type BridgeStep =
  | "MULTI_CHAIN_SELECTION"
  | "SINGLE_CHAIN_SELECTION"
  | "WALLET_SELECTION"
  | "TOKEN_SELECTION"
  | "SWAP_SETTINGS"
  | "ACCOUNT_SETTINGS"
  | "SWAP_DETAILS"
  | "SWAP_REVIEW"
  | "PENDING_TRANSACTION";
